apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cnctmachines.cluster.cnct.sds.samsung.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.status.phase
    description: machine status
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: cluster.cnct.sds.samsung.com
  names:
    kind: CnctMachine
    plural: cnctmachines
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterref:
              description: name of the Cluster object this node belongs to
              type: string
            labels:
              type: object
            roles:
              items:
                type: string
              type: array
            sshconfig:
              properties:
                host:
                  type: string
                port:
                  format: int32
                  type: integer
                publichost:
                  type: string
                username:
                  type: string
              type: object
            taints:
              description: The full, authoritative list of taints to apply to the
                corresponding Node.
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            kubernetesVersion:
              description: kubernetes version of the node, should be equal to corresponding
                cluster version
              type: string
            lastUpdated:
              description: When was this status last observed
              format: date-time
              type: string
            phase:
              description: Machine status
              type: string
          required:
          - kubernetesVersion
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
