apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachine
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: master
  namespace: cluster
spec:
  # Add fields here
  roles:
    - etcd
    - master
  instanceType: standard