apiVersion: cluster.cnct.sds.samsung.com/v1alpha1
kind: CnctMachineSet
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: worker-standard
  namespace: cluster
spec:
  # Add fields here
  # selector labels and template metadata labels must match
  replicas: 1
  selector:
    matchLabels:
      nodepool: standard
  machineTemplate:
    metadata:
      labels:
        nodepool: standard
    spec:
      roles:
        - worker
      instanceType: standard
