#!/bin/bash

CURL='curl --fail --show-error -ksLX'
CURL_OPTS=${CURL_OPTS:-""}

DEBUG=${DEBUG:-1}

[[ $DEBUG == 1 ]] && \
  {
    set -o xtrace
    CURL_OPTS+="-vvv"
  }

set -o errexit
set -o nounset
set -o pipefail

DATA=$(cat <<JSON
{
  "name": "${CLUSTER_NAME}",
  "k8s_version": "${K8S_VERSION}",
  "control_plane_nodes": {
    "labels": [
      {
        "name": "cma-ssh-test",
        "value": "true"
      }
    ],
    "instanceType": "standard",
    "count": 1
  },
  "worker_node_pools": [
    {
      "name": "test-pool1",
      "labels": [
        {
          "name": "cma-ssh-test",
          "value": "true"
        }
      ],
      "instanceType": "standard",
      "count": 1
    }
  ]
}
JSON
)

main()
{
  # shellcheck disable=SC2086
  $CURL POST \
    "${CLUSTER_API}/api/v1/cluster" \
    -H 'Cache-Control: no-cache' \
    -H 'Content-Type: application/json' \
    -d "${DATA}" \
    -iks
}

main
