#!/bin/bash

CURL='curl --fail --show-error -ksLX'
CURL_OPTS=${CURL_OPTS:-""}

DEBUG=${DEBUG:-1}

[[ $DEBUG == 1 ]] && \
  {
    set -o xtrace
    CURL_OPTS+="-vvv"
  }

set -o errexit
set -o nounset
set -o pipefail

main()
{
  # shellcheck disable=SC2086
  $CURL GET \
    "${CLUSTER_API}/api/v1/cluster?name=${CLUSTER_NAME}" \
    -H 'Cache-Control: no-cache' \
    -H 'Content-Type: application/json' \
    ${CURL_OPTS}
}

main
